### ISSUE TITLE
rank_label_wrt_dict error

### ISSUE THREAD

**Issue by jonlin91** [tvayer/PSCN#6]
Hi,
Really appreciate the code you've published for your paper! It has been incredibly helpful.

While running the code, I noticed I was getting an intermittent error, saying that certain nodes were not in the graph when calculating `single_source_dijkstra_path_length` in `labeling_to_root`. This error only happened sometimes and when restarting kernels or re-running the code a few times, would disappear and reappear for later runs.

It turns out, there was an issue in `rank_label_wrt_dict`. As you are looping through `all_distinc_labels` (i.e. `list(set(label_dict.values()))`), the labels were not always ordered, which meant that we were looping through the labels in the wrong order. For a small k, this resulted in the vertex of interested having a rank higher than `k` and therefore disappearing from the subgraph of interest. This is why the error would come up. I assume that the error would disappear at times because label_dict is a dictionary so sometimes, and as dictionaries are unordered, the order of the list would change depending on how it was saved in memory at that time.

The simple fix was to add `all_distinc_labels.sort()` after creating `all_distinc_labels`. This has fixed my problem. I was wondering whether this might also affect some results as even though the `k` was large enough to capture the majority of vertices regardless of order, the order of the resulting re-ordered vertices in the normalised receptive fields was not correct?

Note that this didn't happen very often to me but it happened enough for it to break my code 50% of the time.

Hope this helps!

**Comment by tvayer** [comment]
Hi, sorry I completely missed your comment, which is a great one thanks ! It is old stuff I did it quite quickly, thanks for pointing this error !
